const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('codeit', {
  openWorkspace: () => ipcRenderer.invoke('workspace:open'),
  fsList: () => ipcRenderer.invoke('fs:list'),
  fsRead: (p) => ipcRenderer.invoke('fs:read', p),
  fsWrite: (p, c) => ipcRenderer.invoke('fs:write', p, c),
  execRun: (cmd) => ipcRenderer.invoke('exec:run', cmd),
  tasksStart: (cmd) => ipcRenderer.invoke('tasks:start', cmd),
  tasksList: () => ipcRenderer.invoke('tasks:list'),
  tasksTail: (id) => ipcRenderer.invoke('tasks:tail', id),
  tasksKill: (id) => ipcRenderer.invoke('tasks:kill', id),
  opencodeRun: (dir, model, prompt) => ipcRenderer.invoke('opencode:run', dir, model, prompt),
  opencodeCancel: (dir) => ipcRenderer.invoke('opencode:cancel', dir),
  appPaths: () => ipcRenderer.invoke('app:paths'),
  // projects — organized multi-project workflow (local folders + GitHub repos)
  projectsList: () => ipcRenderer.invoke('projects:list'),
  projectsAddLocal: () => ipcRenderer.invoke('projects:add-local'),
  projectsCreateNew: (opts) => ipcRenderer.invoke('projects:create-new', opts),
  projectsPickParentDir: () => ipcRenderer.invoke('projects:pick-parent-dir'),
  projectsActivate: (id) => ipcRenderer.invoke('projects:activate', id),
  projectsRemove: (id) => ipcRenderer.invoke('projects:remove', id),
  projectsRename: (id, name) => ipcRenderer.invoke('projects:rename', id, name),
  projectsPin: (id, filePath) => ipcRenderer.invoke('projects:pin', id, filePath),
  projectsUnpin: (id, filePath) => ipcRenderer.invoke('projects:unpin', id, filePath),
  projectsReveal: (p) => ipcRenderer.invoke('projects:reveal', p),
  projectsGetChat: (id) => ipcRenderer.invoke('projects:get-chat', id),
  projectsSaveChat: (id, msgs) => ipcRenderer.invoke('projects:save-chat', id, msgs),
  chatsSearch: (q) => ipcRenderer.invoke('chats:search', q),
  projectsClone: (repo, parentDir) => ipcRenderer.invoke('projects:clone', repo, parentDir),
  gitInfo: () => ipcRenderer.invoke('git:info'),
  githubRepos: (limit) => ipcRenderer.invoke('github:repos', limit),
  // secrets (OS keychain) — never localStorage
  keysGet: () => ipcRenderer.invoke('keys:get'),
  keysSet: (name, value) => ipcRenderer.invoke('keys:set', name, value),
  // curated tools: catalog, enablement, MCP calls, skills
  toolsCatalog: () => ipcRenderer.invoke('tools:catalog'),
  toolsSetEnabled: (id, enabled, scope) => ipcRenderer.invoke('tools:set-enabled', id, enabled, scope),
  toolsAlwaysAllow: (toolKey) => ipcRenderer.invoke('tools:always-allow', toolKey),
  toolsCall: (serverId, tool, args, approved) => ipcRenderer.invoke('tools:call', serverId, tool, args, approved),
  toolsServerTools: (serverId) => ipcRenderer.invoke('tools:server-tools', serverId),
  skillsList: () => ipcRenderer.invoke('skills:list'),
  buildInfo: () => ipcRenderer.invoke('app:buildinfo'),
  resetData: () => ipcRenderer.invoke('app:reset-data'),
  usageRecord: (ev) => ipcRenderer.invoke('usage:record', ev),
  usageGet: () => ipcRenderer.invoke('usage:get'),
  usageReset: () => ipcRenderer.invoke('usage:reset')
});
